In [1]:
! pip list


Package                           Version
--------------------------------- ------------------
agate                             1.12.0
agate-dbf                         0.2.3
agate-excel                       0.4.1
agate-sql                         0.7.2
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi        

In [2]:
! pip list -v

Package                           Version            Location                                                      Installer
--------------------------------- ------------------ ------------------------------------------------------------- ---------
agate                             1.12.0             C:\Users\prath\AppData\Roaming\Python\Python312\site-packages pip
agate-dbf                         0.2.3              C:\Users\prath\AppData\Roaming\Python\Python312\site-packages pip
agate-excel                       0.4.1              C:\Users\prath\AppData\Roaming\Python\Python312\site-packages pip
agate-sql                         0.7.2              C:\Users\prath\AppData\Roaming\Python\Python312\site-packages pip
aiobotocore                       2.12.3             C:\ProgramData\anaconda3\Lib\site-packages                    conda
aiohappyeyeballs                  2.4.0              C:\ProgramData\anaconda3\Lib\site-packages                    conda
aiohttp                         

#### pip means python install package

In [3]:
import numpy as np
a= [4,56,8,323,12]
print(type(a))
print(len(a))

<class 'list'>
5


In [4]:
# creating a numpy array with the list 
b = np.array(a)

# checking the type of variable 'b'
print(type(b))
print(b)

# len gives back with total element if array is 10
print(len(b))

# total number oof element
print(b.size)

# no. of dimension of the array
print(b.ndim)

# shape of the array
print(b.shape)

<class 'numpy.ndarray'>
[  4  56   8 323  12]
5
5
1
(5,)


In [7]:
b

array([  4,  56,   8, 323,  12])

In [9]:
neslist=[[32,12,34],[6,7,5],[7,5]]
ars=np.array(neslist)
ars
#On purpose: where the 2d array always needs to fulfill the element completely

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [10]:
neslist=[[32,12,34],[6,7,5],[7,5,3]]
arr=np.array(neslist)
arr

array([[32, 12, 34],
       [ 6,  7,  5],
       [ 7,  5,  3]])

In [11]:
print(arr.ndim)
print(len(arr))
print(arr.size)
print(arr.shape)
print(arr.dtype)

2
3
9
(3, 3)
int32


In [12]:
# get "3" out from arr
print(arr[2][2])

3


### % Range vs Arange

In [13]:
print(np.arange(1,61))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]


In [14]:
print(np.arange(1,61).reshape(12,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]
